version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    networks:
      - sakura-network

networks:
  sakura-network:
    name: sakura-network
    external: true